### ISSUE TITLE
PM Notifications

### ISSUE THREAD

**Issue by kawaii** [kawaiiforums/mybb-mint#4]
You should receive a private message when someone sends you some currency. Further extension to this feature might involve only receiving a PM when you are sent a user-configurable amount of minimum currency units. Similarly, when the item trading mechanism is functional, we should alert the user to any trade requests they have received. 

I did not include any plans for MyAlerts integration as of yet as I am aware @euantorano is in the process of rewriting that plugin (although the timescale is unknown).

**Comment by euantorano** [comment]
Yeah, there’s a rewrite started, but I’ve not got too far yet.
